version: '3.8'

services:
  olog-ui:
    build :
      context: .
      dockerfile: Dockerfile
    container_name: olog-ui
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl
      - ./nginx/logs:/var/log/nginx
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    restart: unless-stopped
