services:
  olog-ui:
    container_name: olog-ui
    image: ghcr.io/limestech/olog-ui/docker:latest
    ports:
      - 3000:3000
    environment:
     - NODE_ENV= production
     - VITE_APP_BASE_URL= http://olog:8181/Olog
     - VITE_HOST= olog-ui